frequency: 50  # Tần số cập nhật bộ lọc (Hz)

# Frame
world_frame: "map"           # Frame gốc
odom_frame: "odom"           # Frame odometry
base_link_frame: "base_link" # Frame robot
base_link_output_frame: "base_link" # Frame đầu ra

# Xử lý dữ liệu 2D (nếu robot chỉ hoạt động trên mặt phẳng)
two_d_mode: true 

# Cấu hình thời gian
transform_time_offset: 0.0
transform_timeout: 0.0

# Tích hợp dữ liệu IMU
imu0: "imu/data"  # Topic IMU
imu0_config: [false, false, false,  # x, y, z (position)
              true, true, true,    # roll, pitch, yaw (orientation)
              true, true, true,    # x_dot, y_dot, z_dot (linear velocity)
              false, false, false, # x, y, z (linear acceleration)
              true, true, true]    # Angular velocity

imu0_differential: false
imu0_remove_gravitational_acceleration: true

# Tích hợp dữ liệu GPS
gps0: "gps_data  # Topic GPS
gps0_config: [true, true, false,   # x, y, z (position)
              false, false, false, # roll, pitch, yaw (orientation)
              false, false, false, # x_dot, y_dot, z_dot (linear velocity)
              false, false, false, # x, y, z (linear acceleration)
              false, false, false] # Angular velocity

gps0_differential: false
gps0_queue_size: 10

# Tích hợp dữ liệu Odom
odom0: "/odom"  # Topic Odometry
odom0_config: [true, true, false,  # x, y, z (position)
               false, false, true, # roll, pitch, yaw (orientation)
               true, true, false,  # x_dot, y_dot, z_dot (linear velocity)
               false, false, false,# x, y, z (linear acceleration)
               false, false, true] # Angular velocity

odom0_differential: false
odom0_queue_size: 10

# Noise (Độ nhiễu cảm biến)
imu0_nodelay: false
imu0_queue_size: 10
imu0_relative: true
imu0_noise_covariance: [0.1, 0, 0, 0, 0, 0,
                        0, 0.1, 0, 0, 0, 0,
                        0, 0, 0.1, 0, 0, 0,
                        0, 0, 0, 0.05, 0, 0,
                        0, 0, 0, 0, 0.05, 0,
                        0, 0, 0, 0, 0, 0.05]

gps0_noise_covariance: [0.2, 0, 0,
                        0, 0.2, 0,
                        0, 0, 0.5]

odom0_noise_covariance: [0.1, 0, 0, 0, 0, 0,
                         0, 0.1, 0, 0, 0, 0,
                         0, 0, 0.1, 0, 0, 0,
                         0, 0, 0, 0.05, 0, 0,
                         0, 0, 0, 0, 0.05, 0,
                         0, 0, 0, 0, 0, 0.05]
                         

